### ISSUE TITLE
[FEAT] 미디어 및 정적 파일 처리를 위한 Docker Compose 설정 개선

### ISSUE THREAD

**Issue by hyeonjeong-ko** [Catch-Groom/First-Django-Project#3]
## Background
- Django 프로젝트에서 미디어 파일 업로드와 정적 파일 처리를 위한 Docker 환경을 구축하기 위해 해당 작업을 진행. 현재 파일 처리 설정이 로컬 환경과 클라우드 환경 모두에서 일관되게 동작하도록 개선이 필요
- 이를 통해 개발 및 배포 시 미디어 파일과 정적 파일이 정상적으로 처리될 수 있도록 개선

## Todo
- [x] Docker Compose에서 미디어 파일 처리를 위한 볼륨 설정 추가
- [x] `settings.py` 파일에서 정적 파일 및 미디어 파일 설정 추가
- [x] `docker-compose.yml`에서 볼륨 설정 및 포트 관련 사항 수정
- [x] 미디어 파일 및 정적 파일 처리가 예상대로 동작하는지 테스트

## See also
- [Docker Compose 공식 문서](https://docs.docker.com/compose/)
- [Django 정적 파일 및 미디어 파일 관리 문서](https://docs.djangoproject.com/en/4.0/howto/static-files/)
